### ISSUE TITLE
Swift 4 simultaneous accesses error

### ISSUE THREAD

**Issue by rogomantik** [kokonak/SlidingPuzzleView#1]
at
`swap(&imagePiecesArray[emptyPieceViewIndex], &imagePiecesArray[emptyPieceViewIndex + index])`

can be fixed with [Proposal: SE-0173](https://github.com/apple/swift-evolution/blob/master/proposals/0173-swap-indices.md) 
`imagePiecesArray.swapAt(emptyPieceViewIndex, emptyPieceViewIndex + index)`
or
```
let temp1 = imagePiecesArray[emptyPieceViewIndex]
imagePiecesArray[emptyPieceViewIndex] = imagePiecesArray[emptyPieceViewIndex + index]
imagePiecesArray[emptyPieceViewIndex + index] = temp1
```
crasches  also here 2 occurrences
`swap(&imagePiecesArray[emptyPieceViewIndex], &imagePiecesArray[tapViewIndex])`

The issue can be considered solved

**Comment by kokonak** [comment]
I updated code for that problem
thanks you!
